on:
  workflow_dispatch:
  push:
    tags:
      - "*"

name: 📦 Continuous Deployment

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6

      - name: 🐋 Setup Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: 🔐 Login
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ⏳ Wait for Continuous Integration
        uses: lewagon/wait-on-check-action@78dd4dd5d9b337c14c3c81f79e53bf7d222435c1
        with:
          check-name: "ci"
          wait-interval: 10

          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏗️ Build and Publish
        run: |
          docker buildx build -t banking-backend:${{  github.ref_name }} -t banking-backend:latest --load .

          docker image tag banking-backend ghcr.io/simplytest/banking-backend
          docker push -a ghcr.io/simplytest/banking-backend

      - name: 📦 Deploy
        uses: appleboy/ssh-action@55dabf81b49d4120609345970c91507e2d734799
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}

          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          script: |
            docker stop Banking-Backend-Demo || true
            docker rm Banking-Backend-Demo || true

            docker pull ghcr.io/simplytest/banking-backend:latest
            docker run -d -p 5005:5005 -e "SIMPLYTEST_DEMO=ON" --rm --name=Banking-Backend-Demo ghcr.io/simplytest/banking-backend:latest

#      - name: 🧨 Detect Breaking Changes
#        id: changes
#        uses: simbo/changes-between-tags-action@v1
#        with:
#          tag-pattern: "^[a-zA-Z()]+!:"
#
#      - name: 🧯 Forward Breaking Changes
#        if: contains(steps.changes.outputs.changes, '!')
#        uses: benc-uk/workflow-dispatch@v1
#        with:
#          workflow: cd.yml
#          repo: simplytest/banking-frontend
