on:
  workflow_dispatch:
  push:
    tags:
      - "*"

name: 📦 Continuous Deployment

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🐋 Setup Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: 🔐 Login
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ⏳ Wait for Continuous Integration
        uses: lewagon/wait-on-check-action@369769072fe522a3a8a85c03c96af1e5242a1994 # v1.9.1
        with:
          check-name: "ci"
          wait-interval: 10

          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏗️ Build and Publish
        run: |
          docker buildx build -t banking-backend:${{  github.ref_name }} -t banking-backend:latest --load .

          docker image tag banking-backend ghcr.io/simplytest/banking-backend
          docker push -a ghcr.io/simplytest/banking-backend

      - name: 📦 Deploy
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}

          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          script: |
            docker stop Banking-Backend-Demo || true
            docker rm Banking-Backend-Demo || true
            docker container rm Banking-Backend-Demo || true

            docker pull ghcr.io/simplytest/banking-backend:latest
            docker run -d -p 5005:5005 -e "SIMPLYTEST_DEMO=ON" --rm --name=Banking-Backend-Demo ghcr.io/simplytest/banking-backend:latest

#      - name: 🧨 Detect Breaking Changes
#        id: changes
#        uses: simbo/changes-between-tags-action@v1
#        with:
#          tag-pattern: "^[a-zA-Z()]+!:"
#
#      - name: 🧯 Forward Breaking Changes
#        if: contains(steps.changes.outputs.changes, '!')
#        uses: benc-uk/workflow-dispatch@v1
#        with:
#          workflow: cd.yml
#          repo: simplytest/banking-frontend
