on:
  push:
  pull_request:
  workflow_dispatch:

name: 🧪 Continuous Integration

jobs:
  ci:
    runs-on: ubuntu-latest
    container: fedora:39

    steps:
      - name: 🏗️ Setup Dependencies
        run: |
          dnf install -y java-21-openjdk maven git --setopt=install_weak_deps=False
          alternatives --remove java /usr/lib/jvm/java-17-openjdk-17.0.11.0.9-1.fc38.x86_64/bin/java || true
          dnf remove java-17-openjdk-headless || true
          alternatives --install /usr/bin/java java /usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc39.x86_64/bin/java 210003
          alternatives --set java /usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc39.x86_64/bin/java
          export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc39.x86_64
          export PATH=$JAVA_HOME/bin:$PATH
          echo "JAVA_HOME=/usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc39.x86_64" >> $GITHUB_ENV
          echo "PATH=/usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc39.x86_64/bin:$PATH" >> $GITHUB_ENV
          java -version
          echo "JAVA_HOME is $JAVA_HOME"
          mvn -version
      
      - name: 📥 Checkout
        uses: actions/checkout@v6

      - name: 🛠️ Checkout Workaround
        # The Checkout GitHub action has problems when running inside of a docker container (as we do).
        # see: https://github.com/actions/checkout/issues/363
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: 🧪 Unit Tests
        run: |
          mvn -version
          mvn test -Dtest="CucumberUnitTest" -Dsurefire.failIfNoSpecifiedTests=false

      - name: 🧪 Integration Tests
        run: |
          mvn test -Dtest="CucumberIntegrationTest" -Dsurefire.failIfNoSpecifiedTests=false

      - name: 🔍 Check for duplicate reports
        id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf
        with:
          skip_after_successful_duplicate: true
          concurrent_skipping: "same_content_newer"

      - name: 📋 Unit Test Report
        uses: phoenix-actions/test-reporting@f957cd93fc2d848d556fa0d03c57bc79127b6b5e
        if: steps.skip_check.outputs.should_skip != 'true' && (success() || failure())
        with:
          name: 📋 Unit Test Report
          reporter: java-junit
          path: "**/*CucumberUnitTest.xml"

      - name: 📋 Integration Test Report
        uses: phoenix-actions/test-reporting@f957cd93fc2d848d556fa0d03c57bc79127b6b5e
        if: steps.skip_check.outputs.should_skip != 'true' && (success() || failure())
        with:
          name: 📋 Integration Test Report
          reporter: java-junit
          path: "**/*CucumberIntegrationTest.xml"

      - name: 👀 Sonar Scan
        if: github.ref == 'refs/heads/master'
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONARQUBE_HOST }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Demo-App-backend -Dsonar.projectName='Demo App backend'

      - name: 🤖 Sonar Summary
        if: github.ref == 'refs/heads/master'
        run: |
          {
            echo "### 🤖 Sonar Summary"
            echo "${{ vars.SONARQUBE_HOST }}"
          } >> $GITHUB_STEP_SUMMARY
