on:
  push:
  pull_request:
  workflow_dispatch:

name: 🧪 Continuous Integration

jobs:
  ci:
    runs-on: ubuntu-latest
    container: fedora:43

    steps:
      - name: 🏗️ Setup Dependencies
        run: |
          dnf install -y java-25-openjdk maven git --setopt=install_weak_deps=False
          export JAVA_HOME=$(readlink -f /usr/bin/java | sed 's|/bin/java||')
          export PATH=$JAVA_HOME/bin:$PATH
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
          java -version
          echo "JAVA_HOME is $JAVA_HOME"
          mvn -version


      - name: 📥 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🛠️ Checkout Workaround
        # The Checkout GitHub action has problems when running inside of a docker container (as we do).
        # see: https://github.com/actions/checkout/issues/363
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: 🧪 Unit Tests
        run: |
          mvn -version
          mvn test -Dtest="CucumberUnitTest" -Dsurefire.failIfNoSpecifiedTests=false

      - name: 🧪 Integration Tests
        run: |
          mvn test -Dtest="CucumberIntegrationTest" -Dsurefire.failIfNoSpecifiedTests=false

      - name: 🔍 Check for duplicate reports
        id: skip_check
        uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578 # v5.3.2
        with:
          skip_after_successful_duplicate: true
          concurrent_skipping: "same_content_newer"

      - name: 📋 Unit Test Report
        uses: phoenix-actions/test-reporting@7317eea6e13c47348dd0bb318669485157c518d6 # v16
        if: steps.skip_check.outputs.should_skip != 'true' && (success() || failure())
        with:
          name: 📋 Unit Test Report
          reporter: java-junit
          path: "**/cucumber-reports/CucumberUnitTest.xml"

      - name: 📋 Integration Test Report
        uses: phoenix-actions/test-reporting@7317eea6e13c47348dd0bb318669485157c518d6 # v16
        if: steps.skip_check.outputs.should_skip != 'true' && (success() || failure())
        with:
          name: 📋 Integration Test Report
          reporter: java-junit
          path: "**/cucumber-reports/CucumberIntegrationTest.xml"

      - name: 👀 Sonar Scan
        if: github.ref == 'refs/heads/master'
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONARQUBE_HOST }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Demo-App-backend -Dsonar.projectName='Demo App backend'

      - name: 🤖 Sonar Summary
        if: github.ref == 'refs/heads/master'
        run: |
          {
            echo "### 🤖 Sonar Summary"
            echo "${{ vars.SONARQUBE_HOST }}"
          } >> $GITHUB_STEP_SUMMARY
